[build]
  command = "npm run build"
  publish = "dist"  # or "build", depending on your framework

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
